### ISSUE TITLE
Licensing and selling 

### ISSUE THREAD

**Issue by matwiszynmarek** [openvizsla/ov_ftdi#11]
Good morning,
I have been doing a research about this type of products and I have got a few questions.
1. What are the certifications for this product (I mean EMC, RCC, CE etc.)?
2. What is the license for software and hardware?
3. Is it possible to sell OpenVizsla made by my own production?

I'll be very thankful if you respond me.

Yours sincerely
Marek

**Comment by somehdlguy** [comment]
1. There are no certs that we are aware of. Any certs that were acquired as part of the kickstarter run are unknown to us (and bushing, who would have known, passed away). 
Before you sell anything, you'll need to figure out what certs are required for the jurisdictions you plan to sell to, then acquire said certs.
2. The license varies depending on what part of the repo. Some files are under CC-like terms, some under GPL, some under BSD. Check the license files in the repo.
3. Sure, why not. Just follow the licenses and release any modifications as is required. (though, we'd appreciate patches for the parts of the code under BSD).

I'd suggest that if you are going to production, you consider updating to a newer FPGA, and review the BOM for EOL components. Of course, you would then need to re-debug and requalify the design.
