### ISSUE TITLE
How do I see the analyzed USB datani

### ISSUE THREAD

**Issue by wxh0000mm** [openvizsla/ov_ftdi#21]
Hello:
How should I use the HOST folder to capture USB bus data? Can you give me a HOST computer software?

**Comment by wxh0000mm** [comment]
Could you give me a description document?Tell me how to test the.bin file after the environment has been set up and successfully compiled.

**Comment by ar0mat** [comment]
Hi @wxh0000mm 

The host sotftware is in `software/host`. There is a short description above in a `Wiki` bookmark.

**Comment by wxh0000mm** [comment]
Thank you for your help
