### ISSUE TITLE
"Sigrok integration"

### ISSUE THREAD

**Issue by dogtopus** [openvizsla/ov_ftdi#41]
So I saw

>Integration with sigrok would be nice to show the packet level of USB.

and made [this](https://github.com/dogtopus/usbll2sr) out of boredom.

It's honestly pretty useless since Wireshark already shows the packet-level detail and PCAP won't provide signal integrity stuff. However it still looks cool. If anyone think it's a good idea to include it in the README feel free to do so :stuck_out_tongue_winking_eye:.

**Comment by laf0rge** [comment]
sorry for the late response.  I certainly would appreciate and support any pull request linking to "third party" FOSS that can be used with ov_ftdi.
