### ISSUE TITLE
Errata: bad silk screen on P4 for 1.2v and 5v

### ISSUE THREAD

**Issue by lf-** [openvizsla/ov_ftdi#42]
On the schematic, the label for pin 23 of the header is 1.2v. This is correct according to tracing the trace on my v3.2 board. However, the silk screen on that one says 5v, and the silk screen for pin 24 says 1.2v. These are inaccurate.

**Comment by msweef** [comment]
Thanks, this is adressed in c375a95 which gets merged very soon. - If you are aware of similar silk screen errors, please report.

**Comment by msweef** [comment]
The error has been fixed as a part of https://github.com/openvizsla/ov_ftdi/pull/46 which just was merged.
