### ISSUE TITLE
Question about 3.3 changes

### ISSUE THREAD

**Issue by pk-r7** [openvizsla/ov_ftdi#49]
How critical is the copper thickness on the internal layers? I wanted to do a prototype run based on these changes but small volume and the 1 oz internal seems to be an issue right now. I can get JLCPCB compliant with all the other specifications except 1 oz on the inner layers.

**Comment by laf0rge** [comment]
sorry for the late response, we don't really use the issue tracker as discussion forum much.

I don't think it matters much if you have lower copper thickness.  The only critical part is the space between top and inner layer, as that is relevant to the impedance of the USB traces.
